export const AppEnv = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL!,
  APP_BASE_URL: process.env.NEXT_PUBLIC_APP_BASE_URL!,
  AUTH_SECRET: process.env.NEXT_PUBLIC_AUTH_SECRET!,
  AUTH_GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!,
  AUTH_GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET!,
  MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI!,
} as const;
